### ISSUE TITLE
Config rebuild ignore commit hash

### ISSUE THREAD

**Issue by tomaszkane** [yiisoft/config#149]
### What steps will reproduce the problem?

* Set version in composer.json: `"yiisoft/form": "dev-master#1739d70f221fa720862f1563e1db801d2a80f014"`
* Run `yii-config-rebuild`

### What is the expected result?

* I have code from `dev-master#1739d70f221fa720862f1563e1db801d2a80f014`
* merge-plan contains configs from `dev-master#1739d70f221fa720862f1563e1db801d2a80f014`

### What do you get instead?

* I have code from `dev-master#1739d70f221fa720862f1563e1db801d2a80f014` - OK
* merge-plan contains configs from `dev-master` - not OK - `dev-master` has "di.php", but in `#1739d70...` is missing, so I got error "vendor/yiisoft/form/config/di.php" file does not found."

### Additional info

| Q                | A
| ---------------- | ---
| Version          | 1.3.0
| PHP version      | 8.0
| Operating system | KDE Neon

**Comment by tomaszkane** [comment]
Or I do something wrong :-)

**Comment by vjik** [comment]
It's documented:

> Note: This feature has severe technical limitations, as the composer.json metadata will still be read from the branch name you specify before the hash. You should therefore only use this as a temporary solution during development to remediate transient issues, until you can switch to tagged releases. The Composer team does not actively support this feature and will not accept bug reports related to it.

See [I have locked a dependency to a specific commit but get unexpected results.](https://getcomposer.org/doc/articles/troubleshooting.md#i-have-locked-a-dependency-to-a-specific-commit-but-get-unexpected-results-).
