### ISSUE TITLE
Existed configuration group "does not exist" after update to 1.3.1

### ISSUE THREAD

**Issue by tomaszkane** [yiisoft/config#151]
### What steps will reproduce the problem?

Update package from 1.3.0 to 1.3.1
Have private package with custom config group like "yii2-common"
```json
{
  "extra": {
    "config-plugin-options": {
      "source-directory": "config"
    },
    "config-plugin": {
      "yii2-common": [
        "yii2-common.php"
      ]
    }
  }
}
```
and load this like:
```php
$yiiConfig = new Config(
    paths: new ConfigPaths(__DIR__ . '/../..'),
    environment: YII_ENV,
    modifiers: [
        RecursiveMerge::groups('yii2-common', 'yii2-backend'),
    ],
    mergePlanFile: 'config/.merge-plan.php',
);

$commonConfig = $yiiConfig->get('yii2-common'); // exception, but this group exist in several packages
```

### What is the expected result?

Config works.

### What do you get instead?

Uncaught ErrorException: The "yii2-common" configuration group does not exist. in /var/www/champ/vendor/yiisoft/config/src/FilesExtractor.php:169

### Additional info

| Q                | A
| ---------------- | ---
| Version          | 1.3.1
| PHP version      | 8.0
| Operating system | KDE Neon

**Comment by vjik** [comment]
Done by #152
