### ISSUE TITLE
Duplicate keys

### ISSUE THREAD

**Issue by Mister-42** [yiisoft/config#20]
I have various duplicate keys reports. Since I am not sure in which packages the correction needs to be made, I will list them below.

**Comment by Mister-42** [comment]
```
Duplicate key "yiisoft/view => basePath"
config/packages/yiisoft/view/config/params.php
config/packages/yiisoft/yii-db-migration/config/params.php
```

**Comment by Mister-42** [comment]
```
Duplicate key "Psr\Log\LoggerInterface"
config/packages/yiisoft/log-target-file/config/common.php
config/packages/yiisoft/profiler/config/common.php
```

**Comment by Mister-42** [comment]
`Duplicate key "Psr\EventDispatcher\EventDispatcherInterface" in "config/console/*.php". Configs with the same key: "".`

?????

**Comment by Mister-42** [comment]
```
Duplicate key "Yiisoft\Translator\CategorySource => __class" in
"/yii3/config/packages/yiisoft/yii-dataview/config/web/*.php". Configs with the same key: 
"/yii3/config/packages/yiisoft/view/config/web.php",
"/yii3/config/packages/yiisoft/user/config/web.php",
"/yii3/config/packages/yiisoft/session/config/web.php",
"/yii3/config/packages/yiisoft/csrf/config/web.php",
"/yii3/config/packages/yiisoft/assets/config/web.php".
```

**Comment by filsh** [comment]
Any news on how to fix this problem?

**Comment by samdark** [comment]
@filsh not very precise messages?

**Comment by filsh** [comment]
@samdark when I add to the params in the yii-demo disabling debug for example
```php
// config/params.php
<?php

declare(strict_types=1);

return [
    'mailer' => [
        'adminEmail' => 'admin@example.com',
    ],

    'yiisoft/yii-debug' => [
        'enabled' => false,
    ],
];
```
then an error occurs https://prnt.sc/10wvbr9
ErrorException
Duplicate key "yiisoft/yii-debug => enabled" in "/home/filsh/www/yii-demo/config/packages/yiisoft/yii-debug/params.php". Configs with the same key: "/home/filsh/www/yii-demo/config/params.php", "/home/filsh/www/yii-demo/config/packages/yiisoft/yii-bootstrap5/params.php", "/home/filsh/www/yii-demo/config/packages/yiisoft/yii-debug-api/params.php", "/home/filsh/www/yii-demo/config/packages/yiisoft/profiler/params.php".

So there is no way to override package params using a parameter from the application

**Comment by samdark** [comment]
Ah, yes. That is expected. Package parameters are coped to the application where you can modify them.

**Comment by samdark** [comment]
The messages are now better. Would you please re-check it, @Mister-42?
