### ISSUE TITLE
Dist files aren't updated

### ISSUE THREAD

**Issue by samdark** [yiisoft/config#25]
1. Checkout https://github.com/yiisoft/app/commit/0afae422ba354065aa78a0bdddb7be291c54e032 with outdated configs and dist files.
2. composer install - no update of dist.
3. composer update - no update of dist.

**Comment by samdark** [comment]
https://github.com/yiisoft/config/issues/23

**Comment by Mister-42** [comment]
https://github.com/yiisoft/app/blob/master/composer.json#L70

**Comment by samdark** [comment]
Yep. Adjusted it.
