### ISSUE TITLE
Having less files in the app

### ISSUE THREAD

**Issue by samdark** [yiisoft/config#29]
While https://github.com/yiisoft/config/pull/16 has drawbacks the idea of having less files in your app is alright. Let's collect ideas in this issue.

**Comment by samdark** [comment]
## No app configs by default

1. We can copy only `.dist` by default. If application config is missing, we can use config from vendor as is.
2. Having your own config will be as easy as copying `.dist` and renaming it. In order for it to be convenient, we need to switch from `dist` directory do `.dist.php` file extension.

**Comment by samdark** [comment]
See https://github.com/yiisoft/config/issues/42

**Comment by viktorprogger** [comment]
One more proposal: #44

**Comment by samdark** [comment]
Closed in favor of #44.
