### ISSUE TITLE
Implement config updates

### ISSUE THREAD

**Issue by samdark** [yiisoft/config#3]
In case package was updated and old config is already in the application, we need to:

1. Add new keys from package config to application config.
2. Comment-out keys that aren't present.
3. Probably report on the differences?

**Comment by yiiliveext** [comment]
English: A decision on the update configuration packages.
Version 1. Copy the additional configs to the subfolder `/config/yii-debug/readonly` - these will be the original default configs. On composer update, we make a diff between the new default configs and the current configs from readonly folder. And then `array_merge($diff, $edited_config)`
Version 2. Before updating the packages, copy the current default configs somewhere in the runtime folder or save in memory. Then we do as in the first version.
