### ISSUE TITLE
Explicitly name container configs

### ISSUE THREAD

**Issue by samdark** [yiisoft/config#43]
## Problem

It's not obvious which config configures container and which is params.

## Proposal

Rename configs:

- `common.php` -> `container-common.php`
- `web.php` -> `container-web.php`
- `console.php` -> `container-console.php`

**Comment by yiiliveext** [comment]
`params.php` -> `service-params.php`

**Comment by vjik** [comment]
> `params.php` -> `service-params.php`

Why? Parameters only one file.

**Comment by samdark** [comment]
I think now with the guide update it's not an issue so leaving file names as is it now.
