### ISSUE TITLE
Improve config diff logic

### ISSUE THREAD

**Issue by viktorprogger** [yiisoft/config#44]
In my opinion we can fully remove `dist` directories/files from a project instead of #42. Not just remove, but replace with another functionality.

I see 6 use-cases to activate this package as a composer plugin:
1. `composer install` when `composer.lock` exists
1. `composer install` when `composer.lock` **does not** exist
1. `composer update`
1. `composer require` an existing package, but in another version
1. `composer require` a new package
1. `composer require yiisoft/config`

- In case 1 this package should do nothing. All the packages had been installed earlier, and their configs - too.
- Cases 2-4 looks similar for me: it's about package(s) updating. In this case the `config` package should provide the choice for a user (read below about it).
- In the cases 5 and 6 the `config` package should copy all the configurations from the `vendor` directory (for a single package in case 5 and for all the packages in case 6), and ask a user what to do when a file with the required name exists in a project.

#### Let's talk about the logic when the plugin sees some differences
When there are some differences, the plugin should ask a user what to do. All available variants are:
- Show diff between a local (in -project) version and a new version (in the `vendor` directory after package updating/requiring).
- Show diff between an old version (copied *before* package update) and a new version
- Replace local version with a new version *(default when there was no local version)*
- Copy a new version to a project with different name. This file shouldn't be included to the merge plan
- Ignore, do nothing *(default when there is a local config version)*
- 3 previous variants, but "For all" (ignore/copy/replace for this and all the future questions)

When a composer command is executed in a non-interactive mode, then the `config` package should automatically choose the default variant.

**Comment by samdark** [comment]
Seems to be entirely possible if `PRE_PACKAGE_INSTALL` and `PRE_PACKAGE_UPDATE` are executed **before** new files are fetched into vendor. This way we can get config we're updating from and, indeed, we don't need `dist` in this case.

**Comment by samdark** [comment]
Interactive IO is possible as well with:

```php
/** @var IOInterface $io */
$io->ask('bla-bla');
```

**Comment by samdark** [comment]
As an additional variant we can have an option not to skip copying default config (or all default configs).
