### ISSUE TITLE
Store vendor configs hash, use it to determine if file was changed

### ISSUE THREAD

**Issue by samdark** [yiisoft/config#55]
In order to improve experience we can store config hash in a file similar to `composer.lock` and then use it to determine if there were changes in vendor config. The goal is not to display any warnings if config is a custom one and vendor did not change since last time.

**Comment by samdark** [comment]
Alternatively it could be stored as a key in merge plan.

**Comment by vjik** [comment]
This should work not line ending sensitive.

**Comment by samdark** [comment]
See https://github.com/yiisoft/config/issues/44#issuecomment-816920589. Likely we can avoid it.
