### ISSUE TITLE
Inconvenient use of the environment

### ISSUE THREAD

**Issue by thenotsoft** [yiisoft/config#99]
Now when using an environment, prod, dev, test or stage, throws an exception if the environment is not specified in composer.json "config-plugin-environments". But if you just specify the environment with an empty value 

```json
"config-plugin-environments": {
        "test": {},
        "dev": {},
        "prod": {}
}
```
 it does not get into the merge-plan, you need to include the config file.

I expect that if no environment exists, it will take the default "/", or add the ability to specify a group of environments that take the same configs, for example prod and stage.

**Comment by samdark** [comment]
Yes. That would be way more convenient.
